include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = BloardFlipswitch
BloardFlipswitch_FILES = Switch.x
BloardFlipswitch_FRAMEWORKS = UIKit
BloardFlipswitch_LIBRARIES = flipswitch
BloardFlipswitch_INSTALL_PATH = /Library/Switches

include $(THEOS)/makefiles/bundle.mk
